apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-chromenode-develop
  labels:
    app: selenium-chromenode-develop
spec:
  selector:
    matchLabels:
      app: selenium-chromenode-develop
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: selenium-chromenode-develop
    spec:
      containers:
        - name: selenium
          image: nexus-registry.codikup-qa.com/admin/registry-default/selenium/node-chrome:latest
          ports:
            - containerPort: 4442
            - containerPort: 4443
            - containerPort: 4444
      volumes:
        - name: selenium-chromenode-config
          configMap:
            name: selenium-chromenode-config
      imagePullSecrets:
        - name: registry-default
      nodeSelector:
        tier: develop
