apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-app-develop
  labels:
    app: work-app-develop
spec:
  selector:
    matchLabels:
      app: work-app-develop
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: work-app-develop
    spec:
      containers:
        - name: testapp
          image: nexus-registry.codikup-qa.com/admin/registry-default/testapp:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: registry-default
      nodeSelector:
        tier: develop
